name: Generate Documentation

on:
    workflow_call:

jobs:
    default:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Generate Documentation
              shell: pwsh
              run: |
                ./bin/doxygen/doxygen.exe ../src/ToolsBox/Doxyfile
            
            - name: Upload Documentation
              uses: actions/upload-artifact@v4
              with:
                name: ToolsBox-Documentation
                path: docs/html/