name: Create Release

on:
  workflow_dispatch:
    inputs:

      tag:
        description: "Tag of the release"
        required: true
        type: string

      title:
        description: "Title of the release"
        required: false
        default: "Default Release"
        type: string
      
      pre-release:
        description: "Is the release a Pre-Release ?"
        required: false
        default: false
        type: boolean


permissions:
  contents: write


jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  create-documentation:
    uses: ./.github/workflows/generate_documentation.yml

  create_release:
    needs: 
      - build
      - create-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: ToolsBox-*
          path: dist
          merge-multiple: true
          ref: ${{ inputs.tag }}

      - name: Compress File
        shell: cmd
        run: |
          mkdir dist/ToolsBox_Release
          mkdir dist/ToolsBox_Release/include
          mkdir dist/ToolsBox_Release/lib
          mkdir dist/ToolsBox_Release/Examples
          mkdir dist/ToolsBox_Release/docs

          xcopy ./src\ToolsBox/*.h dist/ToolsBox_Release/include /S /Y
          xcopy ./src\ToolsBox/*.inl dist/ToolsBox_Release/include /S /Y

          copy ./README.md dist/ToolsBox_Release

          xcopy ./src/Examples dist/ToolsBox_Release/Examples /S /Y

          xcopy dist/ToolsBox-Documentation/docs dist/ToolsBox_Release/docs /S /Y
          xcopy dist/ToolsBox-Windows-x64.lib dist/ToolsBox_Release/lib

          powershell Compress-Archive dist/ToolsBox_Release dist/ToolsBox_Release.zip -Force


      - name: Release On Github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.title }}
          prerelease: ${{ inputs.pre-release }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            dist/ToolsBox-Windows-x64.lib
            dist/ToolsBox-Linux-x64.a
            dist/ToolsBox-macOS-x64.a
            dist/ToolsBox_Release.zip
